<a href="https://colab.research.google.com/github/abhishekanand04/Python-Libraries/blob/feature/Oct24_Numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
b = np.sort(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [ ]:
a.sort() # sorting is performed inplace
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([[1,15,3], [2,5,1], [400, 200, 300]])
a

array([[  1,  15,   3],
       [  2,   5,   1],
       [400, 200, 300]])

In [ ]:
np.sort(a, axis=0) # sorting every column

array([[  1,   5,   1],
       [  2,  15,   3],
       [400, 200, 300]])

In [ ]:
np.sort(a, axis=1) # sorting every row

array([[  1,   3,  15],
       [  1,   2,   5],
       [200, 300, 400]])

HW - How to do sorting in descending order.

In [ ]:
a = np.array([[23, 4,   43],
              [12, 89,  3],
              [69, 420, 0]])

b = np.sort(a)
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
#   [[  0,   3,   4],
#    [ 12,  23,  43],
#    [ 69,  89, 420]]

In [ ]:
x = np.array([[], []])
x

array([], shape=(2, 0), dtype=float64)

In [ ]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [ ]:
a * 5   # Multiply 5 in all elements of a

array([ 5, 10, 15, 20, 25])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
b = np.arange(6, 11)
b

array([ 6,  7,  8,  9, 10])

In [ ]:
a * b # Element wise multiplication between a & b

array([ 6, 14, 24, 36, 50])

In [ ]:
c = np.array([1, 2, 3])
c

array([1, 2, 3])

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a * c

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [ ]:
d = np.arange(12).reshape(3, 4)
e = np.arange(13, 25).reshape(3, 4)
print(d)
print("----------")
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
----------
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [ ]:
d * e # Element wise multiplication between d & e

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [ ]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
d * 5 # Multiply 5 in all elements of d

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [ ]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
e

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
d + e # Element wise addition between d & e

array([[13, 15, 17, 19],
       [21, 23, 25, 27],
       [29, 31, 33, 35]])

In [ ]:
a = np.arange(1,13).reshape((3,4))
c = np.arange(2,14).reshape((4,3))

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
np.dot(a, c)  # Matrix Multiplication

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
np.matmul(a, c) # Matrix Multiplication

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
a @ c   # Matrix Multiplication (Shortcut for matmul())

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [ ]:
a @ 5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
np.dot(a, 5)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [ ]:
# dot() function supports the vector multiplication with a scalar value, which is not possible with matmul().
# Vector * Vector will work for matmul() but Vector * Scalar won't.

In [ ]:
A = np.arange(10).reshape(5,2)
B = np.arange(2).reshape(2,1)
print(np.dot(A,B))

[[1]
 [3]
 [5]
 [7]
 [9]]


In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
B

array([[0],
       [1]])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2
    return x

In [ ]:
random_operation(10)

12

In [ ]:
random_operation(9)

7

In [ ]:
b = [3, 5, 2]
for i in range(len(b)):   # Iterate over all elements
  print(random_operation(b[i]))

1
3
4


In [ ]:
random_operation(b)

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [ ]:
random_operation(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2
    return x

In [ ]:
cool_operation = np.vectorize(random_operation) # Converts a function to vectorised function

In [ ]:
type(cool_operation)

numpy.vectorize

In [ ]:
cool_operation(a)

array([ 2, -1,  4,  1,  6,  3,  8,  5, 10,  7])

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
b

[3, 5, 2]

In [ ]:
cool_operation(b)

array([1, 3, 4])

In [ ]:
def random_operation2(x, y):
    if x % 2 == 0 and y % 2 == 0:
        x += 2
    else:
        x -= 2
    return x

In [ ]:
cool_operation2 = np.vectorize(random_operation2)

In [ ]:
cool_operation2(a)

TypeError: random_operation2() missing 1 required positional argument: 'y'

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
def solve(x):
    return x.sum() + x.max()

In [ ]:
v_solve = np.vectorize(solve)

In [ ]:
A = np.arange(10).reshape(5,2)

In [ ]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
v_solve(A)

AttributeError: 'int' object has no attribute 'sum'

In [ ]:
solve(A)

54

In [ ]:
cool_operation(A)

array([[ 2, -1],
       [ 4,  1],
       [ 6,  3],
       [ 8,  5],
       [10,  7]])

In [ ]:
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2
    return x

In [ ]:
a = np.arange(1,13).reshape((3,4))
c = np.arange(2,14).reshape((4,3))

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.tile(np.arange(0,40,10), (3,1))
b

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
d = np.arange(0,40,10)
d

array([ 0, 10, 20, 30])

In [ ]:
# np.tile(array, (repetition_rows, repetition_cols))

In [ ]:
b = np.tile(np.arange(0,40,10), (1,3))
b

array([[ 0, 10, 20, 30,  0, 10, 20, 30,  0, 10, 20, 30]])

In [ ]:
d

array([ 0, 10, 20, 30])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a + d

array([[ 1, 12, 23, 34],
       [ 5, 16, 27, 38],
       [ 9, 20, 31, 42]])

In [ ]:
e = np.arange(1, 6)
e

array([1, 2, 3, 4, 5])

In [ ]:
a + e

ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

In [ ]:
t = np.array([0,10,20,30]).reshape(4,1)
t

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
e

array([1, 2, 3, 4, 5])

In [ ]:
t + e

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [ ]:
k = np.array([0,10,20,30]).reshape(2,2)
k

array([[ 0, 10],
       [20, 30]])

In [ ]:
t

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
t + k

ValueError: operands could not be broadcast together with shapes (4,1) (2,2) 

In [ ]:
A = np.arange(12).reshape(3, 4)
B = np.array([1, 2, 3])
print(A+B)

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [ ]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
B

array([1, 2, 3])

In [ ]:
# import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [ ]:
x

array([[200, 200, 200],
       [300, 300, 300],
       [400, 400, 400]])

In [ ]:
v

array([200, 300, 400])

In [ ]:
x/v

array([[1.        , 0.66666667, 0.5       ],
       [1.5       , 1.        , 0.75      ],
       [2.        , 1.33333333, 1.        ]])

In [ ]:
v[:,None]

array([[200],
       [300],
       [400]])

In [ ]:
x / v[:,None]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
print((x / v[:,None])[1][1])

1.0
