<a href="https://colab.research.google.com/github/abhishekanand04/Python-Libraries/blob/feature/Oct_24_Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2

4

In [ ]:
import numpy as np
a = np.array(range(16))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
a.shape

(16,)

In [ ]:
a.ndim

1

In [ ]:
a.reshape(8, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(5, 3)

ValueError: cannot reshape array of size 16 into shape (5,3)

In [ ]:
a.reshape(2, 8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(4, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(-1, 2)  # -1 will calculate len(a) / 2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(-1, 3)

ValueError: cannot reshape array of size 16 into shape (3)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
len(a)

16

In [ ]:
b = a.reshape(-1, 2)

In [ ]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
len(b)

8

In [ ]:
len(b[0])

2

In [ ]:
len(b[1])

2

In [ ]:
b.shape

(8, 2)

In [ ]:
np.array(b).size  # Total count of elements


16

In [ ]:
# len(a) -> Count of rows
# len(a[0]) -> Count of columns
# a.shape -> Count of (row, col)
# np.array(a).size  -> Total count of elements
# a.size

In [ ]:
a = np.array(range(100))
a.reshape(25, 4) # 10, 10

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [ ]:
a.reshape(33, 3)

ValueError: cannot reshape array of size 100 into shape (33,3)

In [ ]:
a.reshape(10, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
a.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [ ]:
a.size

100

In [ ]:
b.size

16

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a_transpose = a.T
a_transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[1][2]

6

In [ ]:
a[1, 2] # a[i][j] = a[i, j]

6

In [ ]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b[[3, 5, 1]]  # Accessing multiple elements in 1D array.

array([3, 5, 1])

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# (0, 1), (1, 2), (2, 0)
a[[0, 1, 2], [1, 2, 0]]

array([1, 6, 8])

In [ ]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# x[index] -> 1 element
# x[ list of indexs ] -> multiple elements
lst = [4, 0, 1]
x[lst]

array([4, 0, 1])

In [ ]:
y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# y[i, j] -> 1 element
# y[ list of rows, list of columns ] -> multiple elements
rows = [2, 0, 1]
cols = [0, 1, 1]
# (2, 0), (0, 1), (1, 1)
y[rows, cols]

array([8, 1, 5])

In [ ]:
rows = [2, 0, 1, 0]
cols = [0, 1, 1]
y[rows, cols]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (4,) (3,) 

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x[2:5]

array([2, 3, 4])

In [ ]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
y[:2] # row = 0, 1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
y[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
y[ :, :2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# [start, end, jump]  -> start to (end - 1)
y[1:3, 0:2]

array([[4, 5],
       [8, 9]])

In [ ]:
y[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# a[row slicing, col slicing]

In [ ]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[:, 2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
a[:2, 2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [ ]:
a = np.arange(30).reshape(10,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
a[2:8:2, 1:]
# [ 6,  7,  8],
# [12, 13, 14],
# [18, 19, 20],

array([[ 7,  8],
       [13, 14],
       [19, 20]])

In [ ]:
a = [1, 2, 3, 4, 5]
b = [8, 7, 6]
a[3:] = b[::-2]
print(a)

# a[3:] -> 4, 5
# b[::-2] -> 6, 8

[1, 2, 3, 6, 8]


In [ ]:
a = np.arange(30).reshape(10,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
a[-5:]

array([[15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
a[-5::2]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

In [ ]:
a[::-1]

array([[27, 28, 29],
       [24, 25, 26],
       [21, 22, 23],
       [18, 19, 20],
       [15, 16, 17],
       [12, 13, 14],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [ ]:
a[::-1, ::-1]

array([[29, 28, 27],
       [26, 25, 24],
       [23, 22, 21],
       [20, 19, 18],
       [17, 16, 15],
       [14, 13, 12],
       [11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [ ]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
x = np.arange(10, 20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x < 15

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [ ]:
x[x < 15]

array([10, 11, 12, 13, 14])

In [ ]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [ ]:
a < 10

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
a[a < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0) # even elements
a[mask] = -1

In [ ]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
# Aggregate Functions
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sum(a) # Sum of elements of a

55

In [ ]:
np.mean(a)  # Mean/Average of elements of a

5.5

In [ ]:
print(np.sum(a))

55


In [ ]:
np.min(a)

1

In [ ]:
np.max(a)

10

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.sum(a)

66

In [ ]:
# axis
np.sum(a, axis = 0) # Sum for every colum -> Row wise sum

array([12, 15, 18, 21])

In [ ]:
np.sum(a, axis = 1) # Sum of every row -> Column wise sum

array([ 6, 22, 38])

In [ ]:
# if (condition1 or condition2 or condition3) -> True if anyone of the condition is True
# if (condition1 and condition2) -> True if all of the condition is True

In [ ]:
# Prices of items on your shopping list
prices = np.array([50, 45, 25, 20, 35])

# Your budget
budget = 30

# Check if there's at least one item you can afford
can_afford = np.any(prices <= budget)

if can_afford:
    print("You can buy at least one item on your list!")
else:
    print("Sorry, nothing on your list fits your budget.")

You can buy at least one item on your list!


In [ ]:
# Prices of items on your shopping list
prices = np.array([50, 45, 55, 200, 35])

# Your budget
budget = 30

# Check if there's at least one item you can afford
can_afford = np.any(prices <= budget)

if can_afford:
    print("You can buy at least one item on your list!")
else:
    print("Sorry, nothing on your list fits your budget.")

Sorry, nothing on your list fits your budget.


In [ ]:
# Chores status: 1 for done, 0 for not done
chores = np.array([1, 1, 1, 1, 0])

# Check if all chores are done
all_chores_done = np.all(chores == 1)

if all_chores_done:
    print("Great job! You've completed all your chores. Time to play!")
else:
    print("Finish all your chores before you can play.")

Finish all your chores before you can play.


In [ ]:
# Chores status: 1 for done, 0 for not done
chores = np.array([1, 1, 1, 1, 1])

# Check if all chores are done
all_chores_done = np.all(chores == 1)

if all_chores_done:
    print("Great job! You've completed all your chores. Time to play!")
else:
    print("Finish all your chores before you can play.")

Great job! You've completed all your chores. Time to play!


In [ ]:
# Prices of items on your shopping list
prices = np.array([50, 45, 55, 200, 35])

# Your budget
budget = 30

# Check if there's at least one item you can afford
can_afford = np.any(prices <= budget) or np.any(prices > 10)

if can_afford:
    print("You can buy at least one item on your list!")
else:
    print("Sorry, nothing on your list fits your budget.")

You can buy at least one item on your list!


In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [ ]:
(a <= b)

array([ True,  True,  True,  True])

In [ ]:
(b <= c)

array([ True,  True,  True,  True])

In [ ]:
# Check if all elements of a are less than all elements of b
np.all(a <= b)

True

In [ ]:
(a <= b).all()

True

In [ ]:
((a <= b) & (b <= c)).all()

True

In [ ]:
((a <= b) & (b <= c))

array([ True,  True,  True,  True])

In [ ]:
d = (a <= b)
d

array([ True,  True,  True,  True])

In [ ]:
e = (b <= c)
e

array([ True,  True,  True,  True])

In [ ]:
d & e

array([ True,  True,  True,  True])

In [ ]:
(d & e).all()

True

In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4,0])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr[arr > 0] = 1

In [ ]:
arr

array([ -3,   1,   1,   1,  -2,   0, -45, -11,   1,   0])

In [ ]:
arr[arr < 0] = -1
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [ ]:
# np.where(condition, x, y)

# Product prices
prices = np.array([45, 55, 60, 75, 40, 90])

# Apply a 10% discount to prices above $50
discounted_prices = np.where(prices > 50, prices * 0.9, prices)

print("Original prices:", prices)
print("Discounted prices:", discounted_prices)

Original prices: [45 55 60 75 40 90]
Discounted prices: [45.  49.5 54.  67.5 40.  81. ]


In [ ]:
a = np.array([0,2,3])
b = np.array([1,3,5])

a >= b

array([False, False, False])

In [ ]:
x = 5

if x:
  print("Hello")
else:
  print("Bye")

Hello


In [ ]:
arr = np.array([-3, 4, 27, 34, -2, 0, -45, -11, 4, 0])
print(np.where(arr))

# int -> bool => anything other than 0 is True

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [ ]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd


Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 13.5MB/s]


In [ ]:
data = np.loadtxt('/content/fit.txt', dtype='str')

In [ ]:
# Date, Steps, Mood, Calories Burned, Hours of Sleep, Activity Status
data[0:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [ ]:
activity = data[:, -1:]

In [ ]:
print(activity[:10])

[['Inactive']
 ['Inactive']
 ['Inactive']
 ['Inactive']
 ['Active']
 ['Inactive']
 ['Inactive']
 ['Inactive']
 ['Inactive']
 ['Inactive']]


In [ ]:
a = np.array(range(16))

NameError: name 'np' is not defined

In [ ]:
import numpy as np

In [ ]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[a%2 == 0]

array([2, 4, 6, 8])

In [ ]:
a[a%2 == 0] = 1

In [ ]:
a

array([1, 1, 3, 1, 5, 1, 7, 1, 9])

In [ ]:
a[7] = 0
a

array([1, 1, 3, 1, 5, 1, 7, 0, 9])

In [ ]:
a[[7, 6, 4]] = 0
a

array([1, 1, 3, 1, 0, 1, 0, 0, 9])